### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by dailyraisin** [SassDoc/sassdoc-extras#20]
```shell
$ sassdoc --version
2.1.15
```

```shell
$ sassdoc src/
[ERROR] TypeError: undefined is not a function
    at module.exports.exports (/path/to/node_modules/sassdoc/node_modules/sassdoc-theme-default/node_modules/sassdoc-extras/index.js:5:26)
```

**Comment by HugoGiraudel** [comment]
Could you try to reinstall npm modules please?

**Comment by greaterweb** [comment]
Hey @HugoGiraudel, it's actually failing in our CI process so it always has a fresh npm install. 

It may actually be a problem with `sassdoc-theme-default`, @2.3.6 (pass) vs @2.4.0 (failed). For your reference, in our `package.json` we use `"sassdoc": "^2.1.7"` which gives us `sassdoc@2.1.15`.

Thanks in advance!

**Comment by HugoGiraudel** [comment]
Ping @pascalduez, as he bumped the theme yesterday. :)

**Comment by pascalduez** [comment]
Yep, I'm on it, will push a fix in minutes.

**Comment by pascalduez** [comment]
Should be fixed as of `sassdoc-extras@2.4.1`

**Comment by rootical** [comment]
@pascalduez Could you please update the reference in sassdoc-theme-default? Thanks

**Comment by valeriangalliat** [comment]
@rootical `sassdoc-theme-default` have `"sassdoc-extras": "^2.4.0"` in its `package.json` so it will take the latest patch. I believe you just have to reinstall `sassdoc-theme-default`.

**Comment by rootical** [comment]
Thanks, have missed `^` :+1:
