### ISSUE TITLE
Dependency comes with security warning

### ISSUE THREAD

**Issue by dominikwilkowski** [SassDoc/sassdoc-extras#34]
<img width="1001" alt="screen shot 2018-01-06 at 12 31 43 pm" src="https://user-images.githubusercontent.com/1266923/34634978-adacb22a-f2dd-11e7-8922-3af72d0742f4.png">

The dependency `marked` defined [here](https://github.com/SassDoc/sassdoc-extras/blob/master/package.json#L28) is fixed to `^0.3.0`. Consider fixing it to `^0.3.9` to make sure the affected versions below `0.3.9` are not installed.

<img width="333" alt="screen shot 2018-01-06 at 12 32 11 pm" src="https://user-images.githubusercontent.com/1266923/34634987-b5687e04-f2dd-11e7-9e4c-9563988be805.png">

**Comment by pascalduez** [comment]
Hi,

the dependency is not "fixed" actually, it uses the carret notation, which means it will accept any patch on that `0.3.*` range. So just re-installing the package will get `marked` updated.

**Comment by dominikwilkowski** [comment]
Yeah bad wording on my side. Both yes but in the age of `package-lock.json` files upping your local version will install a new version on top. We had this issue in a bunch of our repos where the bad marked version was fixed inside the lock file and reinstalling the lib yielded the same old version again. Not a bit issue, just a thought.

**Comment by pascalduez** [comment]
Just published a `sassdoc-extras@2.4.2` for peace of mind, and as you said update incentive ;)
Thanks for reporting!
